apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}-infra
  annotations:
    "backstage.io/project": ${{ values.project_id | dump }}
    "backstage.io/cloud-run": ${{ values.app_name | dump }}
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: monkmantra/${{ values.app_name }}-iac
  tags:
    - de-ims-infra
spec:
  type: infra
  owner: user:de-ims
  lifecycle: experimental
